Cuando usamos la función get_frame(1) con el parámetro 1 para tomar sólo un frame, el programa se queda esperando infinitamente en queue.get().
Esto pasa casi siempre entre el frame 502 y el 504. Si el parámetro que ponemos es 2 entonces el error no sucede (si se ejecuta el archivo desde driver-camara.py) y toma todas las imágenes correspondientes.
Lo que pasa es que el programa llama al stream_callback_func en el frame 503 pero se queda en esa función indeterminadamente. Para ver esto pusimos un try: self.queue.get(timeout=1) dentro de la función get_frame en la líntea 178 de test.py. La excepción le dice a la función que retorne. Al retornar el programa quiere sacar nuevamente un frame, pero evidentemente el stream_callback_func ya fue iniciado para el frame anterior y por lo tanto tira un error con código 12555(0x310B), que dice "Stream is started and cannot be re-started."
